<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add new book' => 'Добавить книгу',
    'All Time' => 'Все',
    'Are you sure you want to delete this item?' => 'Подтвердите удаление',
    'Are you sure you want to subscribe to this author?' => 'Подтвердите подписку',
    'Auth Key' => 'Ключ авторизации',
    'Author' => 'Автор',
    'Author ID' => 'Идентификатор автора',
    'Authors' => 'Авторы',
    'Book Management' => 'Книжный каталог',
    'Book Management System' => 'Книжный каталог',
    'Books' => 'Книги',
    'Books Count' => 'Книг',
    'Books by ' => 'Книги автора ',
    'By' => 'Автор(ы)',
    'Create Author' => 'Добавить автора',
    'Create Book' => 'Добавить книгу',
    'Created At' => 'Создано',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Error. Please check your phone number.' => 'Ошибка. Проверьте номер телефона.',
    'Explore our Book Collection' => 'Мы предлагаем книги автомобильной тематики',
    'Full Name' => 'Полное имя',
    'ID' => 'Идентификатор',
    'Image' => 'Изображение',
    'Latest Books' => 'Новые поступления',
    'Login' => 'Войти',
    'Logout' => 'Выйти',
    'New book: {title} by {author}' => 'Новая книга: {title} от автора {author}',
    'Password' => 'Пароль',
    'Password Hash' => 'Хэш пароля',
    'Password Reset Token' => 'Токен сброса пароля',
    'Phone' => 'Телефон',
    'Please check your phone to verify your subscription.' => 'Проверьте SMS в телефоне, чтобы подтвердить подписку.',
    'Please fill out the following fields to login' => 'Введите данные вашей учетной записи',
    'Please fill out the following fields to subscribe to author: {author}' => 'Введите ваш номер для подписки на новые книги автора: {author}',
    'Published' => 'Опубликовано',
    'Remember me' => 'Запомнить меня',
    'Reports' => 'Отчет',
    'Save' => 'Сохранить',
    'Subscribe' => 'Подписаться',
    'Subscription' => 'Подписка',
    'Title' => 'Заголовок',
    'Top Authors' => 'Рейтинг авторов',
    'Update' => 'Изменить',
    'Update Book: ' => 'Изменить книгу: ',
    'Updated At' => 'Обновлено',
    'Username' => 'Имя_пользователя',
    'View Details' => 'Подробнее',
    'Welcome!' => 'Добро пожаловать',
    'Year' => 'Год',
    'You are subscribed to Author: {author}' => 'Вы подписались на автора: {author}',
    'You may login with' => 'Демо аккаунт',
    'ISBN' => '',
    'Update Author' => '',
    'Home' => '@@Каталог@@',
    'Manage Subscription' => '@@Подписки@@',
];
