<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add new book' => '',
    'All Time' => '',
    'Are you sure you want to delete this item?' => '',
    'Are you sure you want to subscribe to this author?' => '',
    'Auth Key' => '',
    'Author' => '',
    'Author ID' => '',
    'Authors' => '',
    'Book Management' => '',
    'Book Management System' => '',
    'Books' => '',
    'Books Count' => '',
    'Books by ' => '',
    'By' => '',
    'Create Author' => '',
    'Create Book' => '',
    'Created At' => '',
    'Delete' => '',
    'Description' => '',
    'Error. Please check your phone number.' => '',
    'Explore our Book Collection' => '',
    'Full Name' => '',
    'ID' => '',
    'ISBN' => '',
    'Image' => '',
    'Latest Books' => '',
    'Login' => '',
    'Logout' => '',
    'New book: {title} by {author}' => '',
    'Password' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Phone' => '',
    'Please check your phone to verify your subscription.' => '',
    'Please fill out the following fields to login' => '',
    'Please fill out the following fields to subscribe to author: {author}' => '',
    'Published' => '',
    'Remember me' => '',
    'Reports' => '',
    'Save' => '',
    'Subscribe' => '',
    'Subscription' => '',
    'Title' => '',
    'Top Authors' => '',
    'Update' => '',
    'Update Author' => '',
    'Update Book: ' => '',
    'Updated At' => '',
    'Username' => '',
    'View Details' => '',
    'Welcome!' => '',
    'Year' => '',
    'You are subscribed to Author: {author}' => '',
    'You may login with' => '',
    'Home' => '@@@@',
    'Manage Subscription' => '@@@@',
];
